[package]
name = "rollok"
version = "0.1.0"
authors = ["Brian Ramirez"]
edition = "2021"
description = "A wollok interpreter written in Rust."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
